# Generated by Django 5.0.12 on 2025-03-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_faq_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQS'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
    ]
