# Generated by Django 5.1.7 on 2025-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/default-product-image.jpg', null=True, upload_to='product_images/'),
        ),
    ]
