# Generated by Django 5.0.6 on 2025-04-08 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Product View"),
                            ("search", "Product Search"),
                            ("cart_add", "Added to Cart"),
                            ("cart_remove", "Removed from Cart"),
                            ("purchase", "Product Purchase"),
                            ("rating", "Product Rating"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_behaviors",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="shop_userbe_user_id_689996_idx",
                    ),
                    models.Index(
                        fields=["product", "timestamp"],
                        name="shop_userbe_product_3d5202_idx",
                    ),
                    models.Index(
                        fields=["interaction_type", "timestamp"],
                        name="shop_userbe_interac_1ce380_idx",
                    ),
                ],
            },
        ),
    ]
