# Generated by Django 5.0.6 on 2025-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_userbehavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
